### ISSUE TITLE
README needs update to show latest version

### ISSUE THREAD

**Issue by hmf** [tensorflow/java-ndarray#10]
## Expected Behavior

Have the release in the README up to date

## Actual Behavior

Latest version is 0.3.3 but README shows 0.3.2

## Steps to Reproduce the Problem

See https://mvnrepository.com/artifact/org.tensorflow/ndarray/0.3.3

- Version: 0.3.3
- Platform: Any

**Comment by karllessard** [comment]
Done, thanks @hmf !
